#!/bin/bash
# check for syntax and style all bash script in this directory
# terse output usable under emacs compile mode
while read -r file; do
    bash -n "$file" && shellcheck -f gcc "$file"
done < <(grep -l '^#!/bin/bash$' -- *)
