#!/bin/bash
# Usage: MAKEDAY N
# creates the set of files for day N
n="$1"
[[ $n =~ ^[[:digit:]]+$ ]] || { echo "Usage: MAKEDAY N"; exit 1;}
[[ ${#n} == 1 ]] && n="0$n"

name="day$n"
# The current path must contain the year
[[ $PWD =~ go/([[:digit:]]{4})/ ]] && YYYY=${BASH_REMATCH[1]}

[[ -e "$name/$name.go" ]] && { echo "ABORT: $name already exists"; exit 1;}

mkdir -p "$name"
cp ../TEMPLATES/TEST.go  "$name/${name}_test.go"
cp ../TEMPLATES/utils.go .
sed -r -e "s/YYYY/$YYYY/g" -e "s/dayNN/$name/g" \
    <../TEMPLATES/INIT.go >"$name/$name.go"
touch "$name/input.txt"

echo "Generated $name/$name.go $name/${name}_test.go $name/input.txt in $name/"
