#!/bin/bash
# Usage: MAKEDAY N
# creates the set of files for day N
maketests=true

err() { echo "***ERROR: $*"; exit 1;}

n="$1"
[[ $n =~ ^[[:digit:]]+$ ]] || err "Usage: MAKEDAY N"
[[ ${#n} == 1 ]] && n="0$n"

name="d$n"
nminized="${n#0}"
if [[ $PWD =~ go/([[:digit:]]{4})/ ]]; then
    YYYY=${BASH_REMATCH[1]}
else
    err "The current path must contain the year: $PWD"
fi
if [[ $PWD =~ ^(.*/days)/d ]]; then
    cd "${BASH_REMATCH[1]}" || exit
elif ! [[ $PWD =~ /days ]]; then
    err "MAKEDAY must be run from dir days/"   
fi

[[ -e "$name/$name.go" ]] && err "$name already exists"

mkdir -p "$name"
cp ../../TEMPLATES/utils.go "$name"
sed -r -e "s/YYYY/$YYYY/g" -e "s/NN/${name#d}/g" -e "s/NM/${nminized}/g" \
    <../../TEMPLATES/INIT.go >"$name/$name.go"
sed -r -e "s/YYYY/$YYYY/g" -e "s/NN/${name#d}/g" -e "s/NM/${nminized}/g" \
    <../../TEMPLATES/README-DD.md >"$name/README.md"
touch "$name/input,,.test" "$name/example.txt" 
echo "$name" >>"$name/.gitignore"

echo "Generated $name/$name.go $name/input,,.txt $name/example.txt $name/README.md in $name/"

if "$maketests"; then
    cp ../../TEMPLATES/TEST.go  "$name/${name}_test.go"
else
    echo "To enable tests, do: cp ../../TEMPLATES/TEST.go  $name/${name}_test.go"
fi
