#!/bin/bash
# clean the directories before git-commiting

# first, place ourselves in the dir of the script
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null

# remove non-commitable files
export d
for d in d??; do
    ( cd "$d" || exit 1
      rm -f -- d[0-9][0-9] __debug_bin *~ \#*
    )
done

# check some problematic files do not remain
nfs=$(find -name .nfs\*)
if [[ -n $nfs ]]; then
    echo "### Warning: some .nfs files remain!"
    echo "$nfs"
fi

# check that all GO source files have their TEST: lines completed
missing=$(grep '^// TEST: .*[^[:alnum:]]([[:space:]]*//.*)$' d??/*.go)
if [[ -n $missing ]]; then
    echo "### Warning: some TEST declarations are missing values!"
    echo "$missing"
    echo "=== Please fix them"
fi

for day in d??; do
    day="${d#d}"
    # check that we will not commit the input file
    [[ -s $day/input.txt ]] && echo "### Warning: $day/input.txt present, rename as $day-input,R1,R2.test"
    file=$(echo $day-input,[0-9]*,[0-9]*.test)
    # check that we added the notes for the completed day (when input file exists)
    if [[ -s "$file" ]] then
       if ! grep -q "^- [*][*]d${d}[*][*][[:space:]]*[^[:space:]]" ../README.md; then
           echo "### Warning: missing $day note in ../README.md"
       fi
    fi
done

